sudo: false
language: python

matrix:
  include:
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
      sudo: true

install:
  - pip install tox bumpversion twine

script:
  - tox

after_success:
  # push tag as well
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      python setup.py sdist bdist_wheel ;
      twine upload dist/* ;
    fi
